# Generated by Django 4.2.4 on 2023-09-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100)),
                ('houseNr', models.CharField(blank=True, max_length=10)),
                ('zipCode', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Speacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonePublish', models.BooleanField(default=False)),
                ('accountType', models.IntegerField(choices=[(1, 'Basis'), (2, 'Premium'), (3, 'Company')], default=1)),
                ('policy', models.BooleanField(default=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SpeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('reference', models.TextField(blank=True, max_length=500)),
                ('publication', models.TextField(blank=True, max_length=500)),
                ('contactdetail', models.TextField(blank=True, max_length=500)),
                ('contactform', models.TextField(blank=True, max_length=500)),
                ('exampleLecture', models.TextField(blank=True, max_length=500)),
                ('shortBiography', models.TextField(blank=True, max_length=500)),
                ('longBiography', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded/')),
                ('speacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='rednerin_api.speacher')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlLink', models.URLField(verbose_name='url')),
                ('speacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='rednerin_api.speacher')),
            ],
        ),
        migrations.AddField(
            model_name='speacher',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.speacherinfo'),
        ),
        migrations.AddField(
            model_name='speacher',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject', to='rednerin_api.subject'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialNetworkName', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='icons/')),
                ('speacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialnetwork', to='rednerin_api.speacher')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='photos_uploaded/')),
                ('speacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='rednerin_api.speacher')),
            ],
        ),
    ]
