# Generated by Django 4.2.4 on 2023-08-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rednerin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('houseNr', models.CharField(blank=True, max_length=10)),
                ('zipCode', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('phonePublish', models.BooleanField(default=False)),
                ('option', models.IntegerField(choices=[(1, 'Basis'), (2, 'Premium'), (3, 'Company')], default=1)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('policy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RednerinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('reference', models.TextField(blank=True, max_length=500)),
                ('publication', models.TextField(blank=True, max_length=500)),
                ('contactdetail', models.TextField(blank=True, max_length=500)),
                ('contactform', models.TextField(blank=True, max_length=500)),
                ('exampleLecture', models.TextField(blank=True, max_length=500)),
                ('shortBiography', models.TextField(blank=True, max_length=500)),
                ('longBiography', models.TextField(blank=True, max_length=5000)),
                ('rednerin_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.rednerin')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded/')),
                ('rednerinInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.rednerininfo')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlLink', models.CharField(max_length=100)),
                ('rednerinInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.rednerininfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialNetworkName', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='icons/')),
                ('rednerinInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rednerin_api.rednerininfo')),
            ],
        ),
        migrations.AddField(
            model_name='rednerininfo',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject', to='rednerin_api.subject'),
        ),
    ]
