# Generated by Django 4.2.4 on 2023-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rednerin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speacher',
            name='accountType',
            field=models.CharField(choices=[('BA', 'Basis'), ('PR', 'Premium'), ('CO', 'Company')], default='BA', max_length=2),
        ),
    ]
